name: 'Helm Package and Push Action'
description: 'Package multiple helm charts and push them to any registry supported by helm'
author: 'staysub'
branding:
  color: 'blue'
  icon: 'upload-cloud'
inputs:
  CHART_DIR_PATH_LIST:
    description: 'Multple dir. in your repo containing Chart.yaml you want packaged and pushed'
    required: true
  REGISTRY_URL:
    description: 'Url to your registry'
    required: true
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  
