name: 'Helm command action'
description: 'Issues helm commands against your repo'
author: 'staysub'
branding:
  color: 'blue'
  icon: 'upload-cloud'
inputs:
  COMMANDS:
    description: 'Multi line commands'
    required: true
  REGISTRY_URL:
    description: 'Url to your registry'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  
